<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function jir_blocks_theme($existing, $type, $theme, $path) {
    $request = Drupal::request();

    $host = $request->getSchemeAndHttpHost();
    $currentPath = Drupal::service('path.current')->getPath();
    $aliasPath = Drupal::service('path.alias_manager')->getAliasByPath($currentPath);

    $currentURL = $host . $aliasPath;

    $route_match = Drupal::routeMatch();
    $current_title = Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

    $facebook = 'http://www.facebook.com/sharer/sharer.php?u=' . $currentURL;
    $twitter = 'http://twitter.com/share?url=' . $currentURL . '&text=' . $current_title;
    $linkedin = 'http://www.linkedin.com/shareArticle?url=' . $currentURL . '&title=' . $current_title;
    $google = 'https://plus.google.com/share?url=' . $currentURL;

    $nid = $route_match->getRawParameter('node');
    if ($nid){
        $job = Node::load($nid);
        $categories[] = $job->get('field_employer_sector')->value;
        $query = Drupal::entityQuery('node')
            ->condition('type', 'job')
            ->condition('status', 1)
            ->condition('nid', $nid, '<>')
            ->condition('field_employer_sector', $categories, 'IN')->count(); // array('administration')
        $similar_jobs = $query->execute();
    }

    return [
        'jix_share_buttons' => [
            'variables' => [
              'facebook' => $facebook,
              'twitter' => $twitter,
              'linkedin' => $linkedin,
              'google' => $google
              ]
        ],
        'jix_copyright' => [
              'variables' => [
                'year' => date('Y'),
                'terms' => t('Conditions d\'utilisation'),
                'privacy' => t('Politique de protection des données'),
                'admin' => t('Gestion')
              ]
        ],
        'jix_similar_jobs' => [
            'variables' => [
                'job_id' => $similar_jobs
            ]
        ]
    ];
}